create extension if not exists pgcrypto;

alter table public.chat_profiles
  add column if not exists avatar_path text
  check (avatar_path is null or char_length(avatar_path) between 1 and 500);

create table if not exists public.mission_rooms (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(btrim(name)) between 1 and 40),
  kind text not null check (kind in ('global', 'private')),
  invite_code text unique check (
    invite_code is null or invite_code ~ '^[A-Z0-9]{4,12}$'
  ),
  password_digest text,
  created_by uuid references auth.users(id) on delete set null,
  chat_conversation_id uuid unique references public.chat_conversations(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint mission_room_shape check (
    (kind = 'global' and invite_code is null and password_digest is null)
    or (kind = 'private' and invite_code is not null)
  )
);

create unique index if not exists one_global_mission_room
  on public.mission_rooms (kind)
  where kind = 'global';

create table if not exists public.mission_room_members (
  room_id uuid not null references public.mission_rooms(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (room_id, user_id)
);

create index if not exists mission_members_by_user
  on public.mission_room_members (user_id, joined_at desc);

create table if not exists public.mission_catalog (
  id bigint generated by default as identity primary key,
  title text not null unique check (char_length(btrim(title)) between 1 and 160),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.mission_catalog (title) values
  ('오늘 발견한 파란색을 사진으로 남기기'),
  ('평소 지나치던 예쁜 간판 찾기'),
  ('가장 웃긴 모양의 물건 찾기'),
  ('빨간 물건 5개를 한 장에 담기'),
  ('친구가 골라준 간식 사진 찍기'),
  ('처음 보는 음료를 골라 사진 남기기'),
  ('영화 포스터처럼 사진 찍기'),
  ('오늘 가장 마음에 드는 하늘 찍기'),
  ('서로를 가장 잘 표현하는 물건 찾기'),
  ('평소 가지 않던 길에서 풍경 찍기'),
  ('5,000원 이하 가장 웃긴 물건 찾기'),
  ('같은 장소에서 서로 다른 구도로 찍기')
on conflict (title) do nothing;

create table if not exists public.daily_room_missions (
  id uuid primary key default gen_random_uuid(),
  room_id uuid not null references public.mission_rooms(id) on delete cascade,
  mission_date date not null,
  slot smallint not null check (slot between 1 and 3),
  catalog_id bigint not null references public.mission_catalog(id),
  created_at timestamptz not null default now(),
  unique (room_id, mission_date, slot),
  unique (room_id, mission_date, catalog_id)
);

create table if not exists public.mission_submissions (
  id uuid primary key default gen_random_uuid(),
  room_id uuid not null references public.mission_rooms(id) on delete cascade,
  daily_mission_id uuid not null references public.daily_room_missions(id) on delete restrict,
  author_id uuid not null references auth.users(id) on delete cascade,
  storage_path text not null unique check (char_length(storage_path) between 1 and 500),
  created_at timestamptz not null default now()
);

create index if not exists mission_submissions_room_created
  on public.mission_submissions (room_id, created_at desc);

create table if not exists public.mission_votes (
  submission_id uuid not null references public.mission_submissions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  choice text not null check (choice in ('accepted', 'not_accepted')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (submission_id, user_id)
);

insert into public.mission_rooms (
  id,
  name,
  kind,
  chat_conversation_id
) values (
  '00000000-0000-0000-0000-000000000100',
  'Global Mission Room',
  'global',
  '00000000-0000-0000-0000-000000000001'
)
on conflict (id) do update
  set chat_conversation_id = excluded.chat_conversation_id;

do $$
declare
  legacy record;
  migrated_room_id uuid;
begin
  for legacy in
    select conversation.id as conversation_id,
           conversation.title,
           conversation.created_by,
           invite.invite_code
    from public.chat_conversations conversation
    join public.chat_room_invites invite
      on invite.conversation_id = conversation.id
    where conversation.kind = 'room'
      and not exists (
        select 1
        from public.mission_rooms room
        where room.chat_conversation_id = conversation.id
      )
  loop
    insert into public.mission_rooms (
      name,
      kind,
      invite_code,
      created_by,
      chat_conversation_id
    ) values (
      coalesce(nullif(btrim(legacy.title), ''), '미션 방'),
      'private',
      legacy.invite_code,
      legacy.created_by,
      legacy.conversation_id
    ) returning id into migrated_room_id;

    insert into public.mission_room_members (room_id, user_id, joined_at)
    select migrated_room_id, member.user_id, member.joined_at
    from public.chat_conversation_members member
    where member.conversation_id = legacy.conversation_id
    on conflict do nothing;

    update public.chat_conversations
    set room_id = migrated_room_id::text
    where id = legacy.conversation_id;
  end loop;
end;
$$;

create or replace function public.is_mission_room_member(p_room_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.mission_rooms room
    where room.id = p_room_id
      and (
        room.kind = 'global'
        or exists (
          select 1
          from public.mission_room_members member
          where member.room_id = room.id
            and member.user_id = auth.uid()
        )
      )
  );
$$;

create or replace function public.ensure_daily_room_missions(p_room_id uuid)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  today date := (now() at time zone 'Asia/Seoul')::date;
begin
  if auth.uid() is null then
    raise exception 'authentication_required';
  end if;
  if not public.is_mission_room_member(p_room_id) then
    raise exception 'not_a_room_member';
  end if;

  insert into public.daily_room_missions (
    room_id,
    mission_date,
    slot,
    catalog_id
  )
  select p_room_id,
         today,
         row_number() over (order by md5(p_room_id::text || today::text || catalog.id::text)),
         catalog.id
  from public.mission_catalog catalog
  where catalog.active
  order by md5(p_room_id::text || today::text || catalog.id::text)
  limit 3
  on conflict do nothing;
end;
$$;

create or replace function public.create_mission_room(
  p_name text,
  p_password text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  clean_name text := btrim(p_name);
  clean_password text := nullif(btrim(coalesce(p_password, '')), '');
  new_code text;
  new_room public.mission_rooms%rowtype;
  conversation_id uuid;
begin
  if auth.uid() is null then
    raise exception 'authentication_required';
  end if;
  if char_length(clean_name) not between 1 and 40 then
    raise exception 'invalid_room_name';
  end if;
  if clean_password is not null and char_length(clean_password) > 40 then
    raise exception 'invalid_password';
  end if;

  loop
    new_code := upper(substr(encode(gen_random_bytes(6), 'hex'), 1, 6));
    exit when not exists (
      select 1 from public.mission_rooms where invite_code = new_code
    );
  end loop;

  insert into public.mission_rooms (
    name,
    kind,
    invite_code,
    password_digest,
    created_by
  ) values (
    clean_name,
    'private',
    new_code,
    case when clean_password is null then null else crypt(clean_password, gen_salt('bf')) end,
    auth.uid()
  ) returning * into new_room;

  insert into public.chat_conversations (kind, title, room_id, created_by)
  values ('room', clean_name, new_room.id::text, auth.uid())
  returning id into conversation_id;

  insert into public.chat_room_invites (conversation_id, invite_code)
  values (conversation_id, new_code);

  update public.mission_rooms
  set chat_conversation_id = conversation_id
  where id = new_room.id;

  insert into public.mission_room_members (room_id, user_id)
  values (new_room.id, auth.uid());

  insert into public.chat_conversation_members (conversation_id, user_id)
  values (conversation_id, auth.uid())
  on conflict do nothing;

  perform public.ensure_daily_room_missions(new_room.id);

  return jsonb_build_object(
    'id', new_room.id,
    'name', new_room.name,
    'kind', new_room.kind,
    'code', new_room.invite_code,
    'isLocked', new_room.password_digest is not null,
    'memberCount', 1
  );
end;
$$;

create or replace function public.join_mission_room(
  p_invite_code text,
  p_password text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  clean_code text := upper(btrim(p_invite_code));
  clean_password text := coalesce(p_password, '');
  target public.mission_rooms%rowtype;
  total_members bigint;
begin
  if auth.uid() is null then
    raise exception 'authentication_required';
  end if;
  if clean_code !~ '^[A-Z0-9]{4,12}$' then
    raise exception 'invalid_invite';
  end if;

  select * into target
  from public.mission_rooms
  where invite_code = clean_code
    and kind = 'private';

  if target.id is null then
    raise exception 'invalid_invite';
  end if;
  if target.password_digest is not null
    and crypt(clean_password, target.password_digest) <> target.password_digest then
    raise exception 'wrong_password';
  end if;

  insert into public.mission_room_members (room_id, user_id)
  values (target.id, auth.uid())
  on conflict do nothing;

  insert into public.chat_conversation_members (conversation_id, user_id)
  values (target.chat_conversation_id, auth.uid())
  on conflict do nothing;

  perform public.ensure_daily_room_missions(target.id);

  select count(*) into total_members
  from public.mission_room_members
  where room_id = target.id;

  return jsonb_build_object(
    'id', target.id,
    'name', target.name,
    'kind', target.kind,
    'code', target.invite_code,
    'isLocked', target.password_digest is not null,
    'memberCount', total_members
  );
end;
$$;

create or replace function public.get_mission_state()
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  room_record record;
  result jsonb;
  today date := (now() at time zone 'Asia/Seoul')::date;
begin
  if auth.uid() is null then
    raise exception 'authentication_required';
  end if;

  for room_record in
    select room.id
    from public.mission_rooms room
    where room.kind = 'global'
       or exists (
         select 1
         from public.mission_room_members member
         where member.room_id = room.id
           and member.user_id = auth.uid()
       )
  loop
    perform public.ensure_daily_room_missions(room_record.id);
  end loop;

  select jsonb_build_object(
    'rooms', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', room.id,
          'name', room.name,
          'kind', room.kind,
          'code', room.invite_code,
          'isLocked', room.password_digest is not null,
          'memberCount', case
            when room.kind = 'global' then (select count(*) from public.chat_profiles)
            else (select count(*) from public.mission_room_members member where member.room_id = room.id)
          end,
          'missions', coalesce((
            select jsonb_agg(
              jsonb_build_object(
                'id', daily.id,
                'title', catalog.title,
                'createdAt', daily.created_at,
                'createdByUserId', 'system-daily'
              ) order by daily.slot
            )
            from public.daily_room_missions daily
            join public.mission_catalog catalog on catalog.id = daily.catalog_id
            where daily.room_id = room.id
              and daily.mission_date = today
          ), '[]'::jsonb)
        ) order by case when room.kind = 'global' then 0 else 1 end, room.created_at desc
      )
      from public.mission_rooms room
      where room.kind = 'global'
         or exists (
           select 1
           from public.mission_room_members member
           where member.room_id = room.id
             and member.user_id = auth.uid()
         )
    ), '[]'::jsonb),
    'submissions', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', submission.id,
          'roomId', submission.room_id,
          'missionId', submission.daily_mission_id,
          'authorUserId', submission.author_id,
          'authorName', profile.display_name,
          'storagePath', submission.storage_path,
          'createdAt', submission.created_at,
          'acceptedVotes', (select count(*) from public.mission_votes vote where vote.submission_id = submission.id and vote.choice = 'accepted'),
          'notAcceptedVotes', (select count(*) from public.mission_votes vote where vote.submission_id = submission.id and vote.choice = 'not_accepted'),
          'currentUserVote', (select vote.choice from public.mission_votes vote where vote.submission_id = submission.id and vote.user_id = auth.uid())
        ) order by submission.created_at desc
      )
      from public.mission_submissions submission
      join public.mission_rooms room on room.id = submission.room_id
      join public.chat_profiles profile on profile.user_id = submission.author_id
      where (
        room.kind = 'global'
        and (submission.created_at at time zone 'Asia/Seoul')::date = today
      ) or (
        room.kind = 'private'
        and exists (
          select 1
          from public.mission_room_members member
          where member.room_id = room.id
            and member.user_id = auth.uid()
        )
      )
    ), '[]'::jsonb)
  ) into result;

  return result;
end;
$$;

create or replace function public.create_mission_submission(
  p_room_id uuid,
  p_daily_mission_id uuid,
  p_storage_path text
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  new_id uuid;
  today date := (now() at time zone 'Asia/Seoul')::date;
begin
  if auth.uid() is null then
    raise exception 'authentication_required';
  end if;
  if not public.is_mission_room_member(p_room_id) then
    raise exception 'not_a_room_member';
  end if;
  if p_storage_path !~ ('^' || p_room_id::text || '/' || auth.uid()::text || '/[A-Za-z0-9._-]+$') then
    raise exception 'invalid_storage_path';
  end if;
  if not exists (
    select 1
    from public.daily_room_missions daily
    where daily.id = p_daily_mission_id
      and daily.room_id = p_room_id
      and daily.mission_date = today
  ) then
    raise exception 'invalid_daily_mission';
  end if;

  insert into public.mission_submissions (
    room_id,
    daily_mission_id,
    author_id,
    storage_path
  ) values (
    p_room_id,
    p_daily_mission_id,
    auth.uid(),
    p_storage_path
  ) returning id into new_id;

  return new_id;
end;
$$;

create or replace function public.cast_mission_vote(
  p_submission_id uuid,
  p_choice text
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  target_room uuid;
begin
  if auth.uid() is null then
    raise exception 'authentication_required';
  end if;
  if p_choice not in ('accepted', 'not_accepted') then
    raise exception 'invalid_vote';
  end if;

  select room_id into target_room
  from public.mission_submissions
  where id = p_submission_id;

  if target_room is null or not public.is_mission_room_member(target_room) then
    raise exception 'submission_not_accessible';
  end if;

  insert into public.mission_votes (submission_id, user_id, choice)
  values (p_submission_id, auth.uid(), p_choice)
  on conflict (submission_id, user_id) do update
    set choice = excluded.choice,
        updated_at = now();
end;
$$;

alter table public.mission_rooms enable row level security;
alter table public.mission_room_members enable row level security;
alter table public.mission_catalog enable row level security;
alter table public.daily_room_missions enable row level security;
alter table public.mission_submissions enable row level security;
alter table public.mission_votes enable row level security;

create policy "mission_rooms_select_accessible"
  on public.mission_rooms for select to authenticated
  using (kind = 'global' or public.is_mission_room_member(id));

create policy "mission_members_select_own_rooms"
  on public.mission_room_members for select to authenticated
  using (user_id = auth.uid() or public.is_mission_room_member(room_id));

create policy "mission_catalog_select_authenticated"
  on public.mission_catalog for select to authenticated
  using (active);

create policy "daily_missions_select_accessible"
  on public.daily_room_missions for select to authenticated
  using (public.is_mission_room_member(room_id));

create policy "mission_submissions_select_accessible"
  on public.mission_submissions for select to authenticated
  using (public.is_mission_room_member(room_id));

create policy "mission_votes_select_accessible"
  on public.mission_votes for select to authenticated
  using (
    exists (
      select 1
      from public.mission_submissions submission
      where submission.id = mission_votes.submission_id
        and public.is_mission_room_member(submission.room_id)
    )
  );

revoke all on public.mission_rooms from anon;
revoke all on public.mission_room_members from anon;
revoke all on public.mission_catalog from anon;
revoke all on public.daily_room_missions from anon;
revoke all on public.mission_submissions from anon;
revoke all on public.mission_votes from anon;

grant select on public.mission_rooms to authenticated;
grant select on public.mission_room_members to authenticated;
grant select on public.mission_catalog to authenticated;
grant select on public.daily_room_missions to authenticated;
grant select on public.mission_submissions to authenticated;
grant select on public.mission_votes to authenticated;

revoke all on function public.is_mission_room_member(uuid) from public;
revoke all on function public.ensure_daily_room_missions(uuid) from public;
revoke all on function public.create_mission_room(text, text) from public;
revoke all on function public.join_mission_room(text, text) from public;
revoke all on function public.get_mission_state() from public;
revoke all on function public.create_mission_submission(uuid, uuid, text) from public;
revoke all on function public.cast_mission_vote(uuid, text) from public;

grant execute on function public.is_mission_room_member(uuid) to authenticated;
grant execute on function public.ensure_daily_room_missions(uuid) to authenticated;
grant execute on function public.create_mission_room(text, text) to authenticated;
grant execute on function public.join_mission_room(text, text) to authenticated;
grant execute on function public.get_mission_state() to authenticated;
grant execute on function public.create_mission_submission(uuid, uuid, text) to authenticated;
grant execute on function public.cast_mission_vote(uuid, text) to authenticated;

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
) values (
  'mission-photos',
  'mission-photos',
  false,
  8388608,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
  set public = false,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

create policy "mission_photos_select_members"
  on storage.objects for select to authenticated
  using (
    bucket_id = 'mission-photos'
    and case
      when (storage.foldername(name))[1] ~
        '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
      then public.is_mission_room_member((storage.foldername(name))[1]::uuid)
      else false
    end
  );

create policy "mission_photos_insert_own"
  on storage.objects for insert to authenticated
  with check (
    bucket_id = 'mission-photos'
    and case
      when (storage.foldername(name))[1] ~
        '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
      then public.is_mission_room_member((storage.foldername(name))[1]::uuid)
      else false
    end
    and (storage.foldername(name))[2] = auth.uid()::text
  );

create policy "mission_photos_delete_own"
  on storage.objects for delete to authenticated
  using (
    bucket_id = 'mission-photos'
    and owner_id = auth.uid()::text
  );

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
) values (
  'profile-avatars',
  'profile-avatars',
  false,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
  set public = false,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

create policy "profile_avatars_select_authenticated"
  on storage.objects for select to authenticated
  using (bucket_id = 'profile-avatars');

create policy "profile_avatars_insert_own"
  on storage.objects for insert to authenticated
  with check (
    bucket_id = 'profile-avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "profile_avatars_update_own"
  on storage.objects for update to authenticated
  using (
    bucket_id = 'profile-avatars'
    and owner_id = auth.uid()::text
  )
  with check (
    bucket_id = 'profile-avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

do $$
begin
  alter publication supabase_realtime add table public.mission_rooms;
exception when duplicate_object then null;
end;
$$;

do $$
begin
  alter publication supabase_realtime add table public.mission_room_members;
exception when duplicate_object then null;
end;
$$;

do $$
begin
  alter publication supabase_realtime add table public.daily_room_missions;
exception when duplicate_object then null;
end;
$$;

do $$
begin
  alter publication supabase_realtime add table public.mission_submissions;
exception when duplicate_object then null;
end;
$$;

do $$
begin
  alter publication supabase_realtime add table public.mission_votes;
exception when duplicate_object then null;
end;
$$;
